### ISSUE TITLE
zap_directory cannot manage unwanted subdirectories

### ISSUE THREAD

**Issue by withnale** [nvwls/zap#14]
In the event I am trying to manage a directory with unwanted subdirectories like so...

```ruby
zap_directory '/etc/dir' do 
  action :delete
end
```

 I get the following error...

```
==> client: Error executing action `delete` on resource 'file[/etc/dir/subdir]'

==> client: Errno::EISDIR
==> client: -------------
==> client: Is a directory - read
```

**Comment by nvwls** [comment]
When I've thought about this in the past, I've never come up with a "least surprise" approach to pruning subdirectories.

I'm thinking of adding support for "recursive true".

Also if !recursive, zap_directory should probably *not* raise an exception if it encounters a directory.

**Comment by withnale** [comment]
Hi... 

Whilst removing empty subdirectories would be great, the main problem is that at present zap_directory does not remove unmanaged files in subdirectories. 

It's almost like there might be two config options: 'recursive' to manage the files in subdirectories and 'remove_empty_subdirs'.

Thanks for writing this. After using chef, puppet and salt for years I find it amazing this functionality still isn't in the core product.
Maybe there are two cases here...

1.

**Comment by nvwls** [comment]
I pushed v0.8.0 which adds `recursive` attribute to **zap_directory**.  The default is false.

As this could be very dangerous, the interface could change in the future.  I had contemplated making an integer `depth` attribute to hopefully protect against:

    zap_directory "#{eval_to_nil}/" do
      recursive true
    end

However, even that cannot protect against is dangerous:

    zap_directory "#{eval_to_nil}/" do
      depth 1
    end

As the damage is already done..
