### ISSUE TITLE
Support managing symlinks

### ISSUE THREAD

**Issue by rmoriz** [nvwls/zap#18]
Given a directory /var/log/remote_syslog
That has symlink /var/log/remote_syslog/application1 => /srv/application/logs/application.log
And has symlink /var/log/remote_syslog/application2 => /srv/application/logs/application2.log
And has symlink /var/log/remote_syslog/application3 => /srv/application/logs/application3.log
When the link creation of /var/log/remote_syslog/application3 isn't in the chef context anymore
zap should remove the symlink from /var/log/remote_syslog/application3 to  /srv/application/logs/application3.log

**Comment by nvwls** [comment]
Fixed in v0.10.0
