### ISSUE TITLE
Adding zap onto the end of the resource_collection fails

### ISSUE THREAD

**Issue by sbotman** [nvwls/zap#22]
Seems that the logic within the chef 12 client has changed a little for adding resources to the resource_collection.
https://github.com/chef/chef/blob/master/lib/chef/resource_collection/resource_list.rb#L61

With 12 it's adding resources below the current resource and will converge as soon as the current resource is finished. This will change the behaviour of zap because files/templates that are added later on the resources_collection will be missed and files will be removed (which will be added again later).

Didn't noticed this up until now, because this is depended on the location of the cookbook within the run-list. Just wonder if you have seen this already @nvwls?

**Comment by nvwls** [comment]
We have not upgraded to chef-12 yet.       :-(
