### ISSUE TITLE
Add a zap resource for cron_d LWRP

### ISSUE THREAD

**Issue by patcon** [nvwls/zap#28]
https://github.com/chef-cookbooks/cron

Similar to interface for core cron resource.

Curious whether this would be something you'd accept a PR for, so let me know :)

**Comment by nvwls** [comment]
I’m always willing to look at PRs…

**Comment by nvwls** [comment]
Added `zap::cron_d` recipe in v0.9.0

**Comment by patcon** [comment]
:heart:

**Comment by patcon** [comment]
Finally had a chance to try this out, but seems that it deletes the resources that were just added. It may have something to do with the fact that the `cron_d` resources are added by another provider:

https://github.com/damm/backup/blob/master/providers/generate_model.rb#L33-L58

I'll investigate and try again. I don't suppose there are any other instructions besides added the recipe?

**Comment by patcon** [comment]
So if I create a cron_d resource directly in my recipe, it does work. But if I'm using a resource that in turn uses cron_d, then those cron_d files get blown away. Any advice?

**Comment by patcon** [comment]
Yep, sorry, I'm out of ideas, and don't know enough about chef internals to know which thread to pull here. Let me know if you have any pointers :)
