### ISSUE TITLE
zap_apt_repos broken

### ISSUE THREAD

**Issue by grimm26** [nvwls/zap#33]
https://github.com/chef/chef/pull/4782 seems to have broken zap_apt_repos.
zap_apt_repos will clear out /etc/apt/sources.list.d/ directory because it didn't see anything placed into it through the apt cookbook's apt_repository resource.  The new chef core apt_repository resource has overridden the apt cookbook's apt_repository resource.

**Comment by lamont-granquist** [comment]
likely a dup of #35

**Comment by nvwls** [comment]
Fixed in v1.0.0
