### ISSUE TITLE
Zap cannot cope with chef-client >= 12.14.x

### ISSUE THREAD

**Issue by stefanwb** [nvwls/zap#34]
Due to this addon: https://github.com/chef/chef/pull/5187 zap deletes all the repos when bootstrapping a new instance.

Have to admit that I do not have a in-depth knowledge as to tackle this issue. 

Workaround for now seems to be using chef-client < 12.14.x

**Comment by secmff** [comment]
I have a solution for this, but it requires an API change:
https://github.com/secmff/zap/tree/issue_34

Chef::Resource::User is now just parent of User::Linux and others. I was not able to get provides :user out of those resources. Is there a way to do that?

**Comment by secmff** [comment]
#38
