### ISSUE TITLE
Aborted runs will clean files based on a partial list of files that have run

### ISSUE THREAD

**Issue by lamont-granquist** [nvwls/zap#37]
Again see:

https://github.com/chef/chef/issues/3956

The problem is that delayed notifications will always fire, even if the chef-client run aborts in the middle.

I think you'll probably need core-chef support for doing this.   There is a bug or an RFC somewhere about adding support for not running a delayed notification when the chef-client run fails.  Should probably dig that up and link those two issues, since this is a very good use case for why we should implement that.

**Comment by nvwls** [comment]
`zap` does not run as a delayed notification. When it runs, it appends a `dup` of itself to the run_list:
https://github.com/nvwls/zap/blob/v2.1.3/libraries/default.rb#L87-L96

When `Chef::Provider::Zap` runs it checks if `@delayed`
https://github.com/nvwls/zap/blob/v2.1.3/libraries/default.rb#L87-L96

I have tested this many times and the "delayed" zap does not run.
