### ISSUE TITLE
[Feature Request] zap on Windows

### ISSUE THREAD

**Issue by Demortuus** [nvwls/zap#40]
Hi,
can you make zap work on Windows?
I have the following problem:

zap_directory 'C:\\etc\\sensu\\conf.d\\checks' do
  pattern '*.json'
  notifies :create, 'ruby_block[sensu_service_trigger]', :immediately
end

This deletes all files in the directory, as opposed to garbage collecting the files not used by chef anymore. If I remove a sensu check, the corresponding .json is still in the directory, therefore the check is still active.

**Comment by lamont-granquist** [comment]
most likely this has nothing to do with windows and is a dup of #42

**Comment by nvwls** [comment]
Fixed in v1.0.0
