### ISSUE TITLE
uninitialized constant Chef::ResourceResolver

### ISSUE THREAD

**Issue by wildufo** [nvwls/zap#43]
https://github.com/nvwls/zap/blob/e6058dda8b614f832ea5409d2cb406d242d94d04/libraries/default.rb#L99

**Comment by nvwls** [comment]
What version of chef-client?

**Comment by wildufo** [comment]
Chef: 11.18.0

**Comment by nvwls** [comment]
zap v1.x only works with chef 12 or later.

**Comment by wildufo** [comment]
wonderful. you did that without any warning.
